`timescale 1ns / 1ps

// RMTv3 Action Engine - Simplified with only 8 alu_2_core instances
// Each ALU processes one KV pair from the input KV data packet

module action_engine #(
    parameter STAGE_ID = 0,
    parameter PHV_LEN = 320,
    parameter KV_DATA_WIDTH = 512,
    parameter ACT_LEN = 8,
    parameter ACTION_ID = 3,
    parameter C_S_AXIS_DATA_WIDTH = 512,
    parameter C_S_AXIS_TUSER_WIDTH = 128,
    parameter RAM_ADDR_WIDTH = 14  // 16384 depth (2^14)
)(
    input clk,
    input rst_n,

    // PHV input
    input [PHV_LEN-1:0]           phv_in,
    input                         phv_valid_in,
    
    // KV data input (8 KV pairs)
    input [KV_DATA_WIDTH-1:0]     kv_data_in,
    
    // Action input (fixed, generated by stage)
    input [ACT_LEN*25-1:0]        action_in,
    input                         action_valid_in,
    output                        ready_out,

    // PHV output (metadata may be updated)
    output reg [PHV_LEN-1:0]      phv_out,
    output reg                    phv_valid_out,
    
    // KV data output (values may be updated by query)
    output reg [KV_DATA_WIDTH-1:0] kv_data_out,
    
    input                         ready_in,

    // Control path (not used)
    input [C_S_AXIS_DATA_WIDTH-1:0]				c_s_axis_tdata,
    input [C_S_AXIS_TUSER_WIDTH-1:0]			c_s_axis_tuser,
    input [C_S_AXIS_DATA_WIDTH/8-1:0]			c_s_axis_tkeep,
    input										c_s_axis_tvalid,
    input										c_s_axis_tlast,

    output reg [C_S_AXIS_DATA_WIDTH-1:0]		c_m_axis_tdata,
    output reg [C_S_AXIS_TUSER_WIDTH-1:0]		c_m_axis_tuser,
    output reg [C_S_AXIS_DATA_WIDTH/8-1:0]		c_m_axis_tkeep,
    output reg 								    c_m_axis_tvalid,
    output reg 								    c_m_axis_tlast
);

// ============ PHV/KV Pipeline Registers (4 stages to match ALU latency) ============
// Stage 1-4 registers to delay PHV/KV data
reg [PHV_LEN-1:0] phv_pipe_s1, phv_pipe_s2, phv_pipe_s3, phv_pipe_s4;
reg [KV_DATA_WIDTH-1:0] kv_pipe_s1, kv_pipe_s2, kv_pipe_s3, kv_pipe_s4;
reg [ACT_LEN*25-1:0] action_pipe_s1, action_pipe_s2, action_pipe_s3, action_pipe_s4;

always @(posedge clk) begin
    if (~rst_n) begin
        phv_pipe_s1 <= 0;
        phv_pipe_s2 <= 0;
        phv_pipe_s3 <= 0;
        phv_pipe_s4 <= 0;
        kv_pipe_s1 <= 0;
        kv_pipe_s2 <= 0;
        kv_pipe_s3 <= 0;
        kv_pipe_s4 <= 0;
        action_pipe_s1 <= 0;
        action_pipe_s2 <= 0;
        action_pipe_s3 <= 0;
        action_pipe_s4 <= 0;
    end
    else begin
        // Pipeline stage 1
        phv_pipe_s1 <= phv_in;
        kv_pipe_s1 <= kv_data_in;
        action_pipe_s1 <= action_in;
        // Pipeline stage 2
        phv_pipe_s2 <= phv_pipe_s1;
        kv_pipe_s2 <= kv_pipe_s1;
        action_pipe_s2 <= action_pipe_s1;
        // Pipeline stage 3
        phv_pipe_s3 <= phv_pipe_s2;
        kv_pipe_s3 <= kv_pipe_s2;
        action_pipe_s3 <= action_pipe_s2;
        // Pipeline stage 4
        phv_pipe_s4 <= phv_pipe_s3;
        kv_pipe_s4 <= kv_pipe_s3;
        action_pipe_s4 <= action_pipe_s3;
    end
end

// Use stage 4 (delayed) data for output composition
wire [PHV_LEN-1:0] phv_delayed = phv_pipe_s4;
wire [KV_DATA_WIDTH-1:0] kv_delayed = kv_pipe_s4;
wire [ACT_LEN*25-1:0] action_delayed = action_pipe_s4;

// ============ Extract ib (insertion bitmap) from PHV ============
// PHV structure: [159:128] = ib (index bitmap for aggregation)
//                [223:192] = bitmap (processing bitmap, unused here)
wire [31:0] ib_in = phv_in[159:128];

// ============ Page table (for tenant isolation) ============
// Simplified: single tenant, base_addr=0, len=256
reg [2*RAM_ADDR_WIDTH-1:0] page_tbl_out;
reg page_tbl_out_valid;

always @(posedge clk) begin
    if (~rst_n) begin
        page_tbl_out <= {14'd16383, 14'd0};  // len=16383, base=0
        page_tbl_out_valid <= 1'b1;
    end
end

// ============ Instantiate 8 alu_2_core instances ============
wire [63:0] alu_result [0:7];  // 64-bit to support Swap
wire [7:0] alu_result_valid;
wire [7:0] alu_ready;

// RAM interfaces for each ALU
wire [RAM_ADDR_WIDTH-1:0] alu_load_addr [0:7];
wire [63:0] alu_load_data [0:7];
wire [RAM_ADDR_WIDTH-1:0] alu_store_addr [0:7];
wire [63:0] alu_store_din [0:7];
wire [7:0] alu_store_en;

genvar alu_idx;
generate
    for (alu_idx = 0; alu_idx < 8; alu_idx = alu_idx + 1) begin : kv_alu_array
        
        // Extract operands from KV data directly (no extra delay)
        // FIFO already has inherent delay, PHV/valid must be delayed to match
        wire [31:0] operand_key   = kv_data_in[alu_idx*64 +: 32];
        wire [31:0] operand_value = kv_data_in[alu_idx*64 + 32 +: 32];
        wire [31:0] operand_ib = ib_in;  // Pass ib (insertion bitmap) to ALU
        
        // Instantiate alu_agg (Pipelined ALU for Aggregation and Query)
        alu_agg #(
            .STAGE_ID(STAGE_ID),
            .ACTION_LEN(25),
            .DATA_WIDTH(32),
            .RAM_DATA_WIDTH(64),
            .RAM_ADDR_WIDTH(RAM_ADDR_WIDTH),
            .ACTION_ID(alu_idx)
        ) alu_inst (
            .clk(clk),
            .rst_n(rst_n),
            
            // Action input
            .action_in(action_in[alu_idx*25 +: 25]),
            .action_valid(action_valid_in),
            
            // Operands
            .operand_1_in(operand_key),
            .operand_2_in(operand_value),
            .operand_3_in(operand_ib),  // Pass ib for bitmap updates
            
            // Page table
            .page_tbl_out(page_tbl_out),
            .page_tbl_out_valid(page_tbl_out_valid),
            
            // Output
            .container_out_w(alu_result[alu_idx]),
            .container_out_valid(alu_result_valid[alu_idx]),
            .ready_out(alu_ready[alu_idx]),
            .ready_in(ready_in),
            
            // RAM interface
            .load_addr(alu_load_addr[alu_idx]),
            .load_data(alu_load_data[alu_idx]),
            .store_addr(alu_store_addr[alu_idx]),
            .store_din(alu_store_din[alu_idx]),
            .store_en(alu_store_en[alu_idx])
        );
        
        // Instantiate dedicated True Dual-Port RAM for each ALU (BRAM)
        // Using Xilinx Block Memory Generator IP
        kv_ram_64w_16384d kv_ram (
            // Port A - Write port
            .clka(clk),
            .ena(1'b1),
            .wea(alu_store_en[alu_idx]),
            .addra(alu_store_addr[alu_idx]),
            .dina(alu_store_din[alu_idx]),
            .douta(),  // Not used
            
            // Port B - Read port
            .clkb(clk),
            .enb(1'b1),
            .web(1'b0),  // Read only
            .addrb(alu_load_addr[alu_idx]),
            .dinb(64'b0),  // Not used
            .doutb(alu_load_data[alu_idx])
        );
        
    end
endgenerate

// ============ Update PHV and KV data based on ALU results ============
reg [PHV_LEN-1:0] phv_out_next;
reg [KV_DATA_WIDTH-1:0] kv_data_out_next;
reg phv_valid_out_next;

// Intermediate ib result (for merging multiple ALU results)
reg [31:0] ib_merged;

always @(*) begin
    // Default: pass through delayed data (4-stage delay to match ALU)
    phv_out_next = phv_delayed;
    kv_data_out_next = kv_delayed;
    phv_valid_out_next = 0;
    ib_merged = phv_delayed[159:128];  // Start with delayed ib
    
    // Update based on ALU results
    // Wait for ALL 8 ALUs to complete (synchronous output)
    if (&alu_result_valid) begin  // All 8 ALUs have valid output
        phv_valid_out_next = 1;
        
        // Unroll loop for each ALU (Icarus Verilog requires constant indices)
        // For Hash Aggregation: MERGE all ib results (bitwise AND)
        // For Query: update corresponding value in KV data
        // For Swap: update corresponding KV pair (both key and value)
        if (alu_result_valid[0]) begin
            case (action_delayed[24:21])
                4'b0100: ib_merged = ib_merged & alu_result[0][31:0];  // Hash Agg -> merge ib
                4'b0101: kv_data_out_next[32 +: 32] = alu_result[0][31:0];  // Query -> update value
                4'b0110: kv_data_out_next[0 +: 64] = alu_result[0];  // Swap -> update KV pair
            endcase
        end
        if (alu_result_valid[1]) begin
            case (action_delayed[49:46])
                4'b0100: ib_merged = ib_merged & alu_result[1][31:0];
                4'b0101: kv_data_out_next[96 +: 32] = alu_result[1][31:0];
                4'b0110: kv_data_out_next[64 +: 64] = alu_result[1];  // Swap
            endcase
        end
        if (alu_result_valid[2]) begin
            case (action_delayed[74:71])
                4'b0100: ib_merged = ib_merged & alu_result[2][31:0];
                4'b0101: kv_data_out_next[160 +: 32] = alu_result[2][31:0];
                4'b0110: kv_data_out_next[128 +: 64] = alu_result[2];  // Swap
            endcase
        end
        if (alu_result_valid[3]) begin
            case (action_delayed[99:96])
                4'b0100: ib_merged = ib_merged & alu_result[3][31:0];
                4'b0101: kv_data_out_next[224 +: 32] = alu_result[3][31:0];
                4'b0110: kv_data_out_next[192 +: 64] = alu_result[3];  // Swap
            endcase
        end
        if (alu_result_valid[4]) begin
            case (action_delayed[124:121])
                4'b0100: ib_merged = ib_merged & alu_result[4][31:0];
                4'b0101: kv_data_out_next[288 +: 32] = alu_result[4][31:0];
                4'b0110: kv_data_out_next[256 +: 64] = alu_result[4];  // Swap
            endcase
        end
        if (alu_result_valid[5]) begin
            case (action_delayed[149:146])
                4'b0100: ib_merged = ib_merged & alu_result[5][31:0];
                4'b0101: kv_data_out_next[352 +: 32] = alu_result[5][31:0];
                4'b0110: kv_data_out_next[320 +: 64] = alu_result[5];  // Swap
            endcase
        end
        if (alu_result_valid[6]) begin
            case (action_delayed[174:171])
                4'b0100: ib_merged = ib_merged & alu_result[6][31:0];
                4'b0101: kv_data_out_next[416 +: 32] = alu_result[6][31:0];
                4'b0110: kv_data_out_next[384 +: 64] = alu_result[6];  // Swap
                endcase
            end
        if (alu_result_valid[7]) begin
            case (action_delayed[199:196])
                4'b0100: ib_merged = ib_merged & alu_result[7][31:0];
                4'b0101: kv_data_out_next[480 +: 32] = alu_result[7][31:0];
                4'b0110: kv_data_out_next[448 +: 64] = alu_result[7];  // Swap
            endcase
        end
        
        // Apply merged ib to output PHV
        phv_out_next[159:128] = ib_merged;
    end
end

// Register outputs
always @(posedge clk) begin
    if (~rst_n) begin
        phv_out <= 0;
        phv_valid_out <= 0;
        kv_data_out <= 0;
    end
    else begin
        phv_out <= phv_out_next;
        phv_valid_out <= phv_valid_out_next;
        kv_data_out <= kv_data_out_next;
    end
end

// ready_out: 透传下游的 ready 信号（背压）
// ALU 永远 ready，所以只看下游
assign ready_out = ready_in;

// Control path pass-through (not used)
always @(posedge clk) begin
    if (~rst_n) begin
        c_m_axis_tdata <= 0;
        c_m_axis_tuser <= 0;
        c_m_axis_tkeep <= 0;
        c_m_axis_tvalid <= 0;
        c_m_axis_tlast <= 0;
    end
    else begin
        c_m_axis_tdata <= c_s_axis_tdata;
        c_m_axis_tuser <= c_s_axis_tuser;
        c_m_axis_tkeep <= c_s_axis_tkeep;
        c_m_axis_tvalid <= c_s_axis_tvalid;
        c_m_axis_tlast <= c_s_axis_tlast;
    end
end

endmodule

